/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_api_characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/world": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** World Snapshot */
        get: operations["world_snapshot_api_world_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Character Detail */
        get: operations["character_detail_api_characters__pid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect Char */
        post: operations["connect_char_api_characters__pid__connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect Char */
        post: operations["disconnect_char_api_characters__pid__disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/relocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Relocate Char */
        post: operations["relocate_char_api_characters__pid__relocate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescan Char
         * @description Rebuild the session for a PID so locate can run again.
         *
         *     Used when a tthola.dat process exists but locate retries timed out before the
         *     user logged into a character — the worker thread is dead and there is no
         *     automatic restart path.
         */
        post: operations["rescan_char_api_characters__pid__rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/focus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Focus Window */
        post: operations["focus_window_api_characters__pid__focus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/inventory/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Inventory */
        post: operations["scan_inventory_api_characters__pid__inventory_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/warehouse/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Warehouse */
        post: operations["scan_warehouse_api_characters__pid__warehouse_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_snapshots_get"];
        put?: never;
        /** Save Snapshot */
        post: operations["save_snapshot_api_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Snapshot */
        delete: operations["delete_snapshot_api_snapshots__snapshot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/by-name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Character */
        delete: operations["delete_character_api_characters_by_name__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/by-name/{name}/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Character Account */
        put: operations["set_character_account_api_characters_by_name__name__account_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/autoclick/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_characters__pid__autoclick_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/autoclick/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_characters__pid__autoclick_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/autoclick/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Click */
        post: operations["test_click_api_characters__pid__autoclick_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/autoclick/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_characters__pid__autoclick_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/keep-active/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_characters__pid__keep_active_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/keep-active/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_characters__pid__keep_active_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{pid}/keep-active/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_characters__pid__keep_active_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maps/by-name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map By Name */
        get: operations["map_by_name_api_maps_by_name__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Treasury Summary */
        get: operations["treasury_summary_api_treasury_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Treasury Items */
        get: operations["treasury_items_api_treasury_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Treasury Export Csv
         * @description Treasury report as Excel-friendly CSV. mode=detail|summary (unknown → summary).
         *
         *     Encoded UTF-8 with BOM (utf-8-sig) so Windows Excel (cp950 locale) opens
         *     Chinese names without mojibake. Reuses load_latest_snapshots + _aggregate;
         *     no new aggregation logic.
         */
        get: operations["treasury_export_csv_api_treasury_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Backup */
        get: operations["export_backup_api_backup_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Backup */
        post: operations["import_backup_api_backup_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            /** Account Id */
            account_id: number;
            /** Name */
            name: string;
            /**
             * Character Count
             * @default 0
             */
            character_count: number;
        };
        /** AutoClickConfig */
        AutoClickConfig: {
            /** Interval Ms */
            interval_ms: number;
            /** Merchant Idx */
            merchant_idx: number;
            /**
             * Mode
             * @default off
             * @enum {string}
             */
            mode: "off" | "collect" | "destroy";
            /**
             * Clicks Per Round
             * @default 1
             */
            clicks_per_round: number;
        };
        /** AutoClickStatus */
        AutoClickStatus: {
            /** Running */
            running: boolean;
            /** Started At */
            started_at?: number | null;
            /** Runtime Seconds */
            runtime_seconds?: number | null;
            /** Last Click At */
            last_click_at?: number | null;
        };
        /** AutoClickTestRequest */
        AutoClickTestRequest: {
            /** Merchant Idx */
            merchant_idx: number;
        };
        /** BackupImportResult */
        BackupImportResult: {
            /** Snapshots Added */
            snapshots_added: number;
            /** Snapshots Skipped */
            snapshots_skipped: number;
            /** Accounts Added */
            accounts_added: number;
            /** Characters Assigned */
            characters_assigned: number;
            /** Account Conflicts */
            account_conflicts: number;
        };
        /** Body_import_backup_api_backup_import_post */
        Body_import_backup_api_backup_import_post: {
            /** File */
            file: string;
        };
        /**
         * BuffInfo
         * @description One active status on a character. The game stores the status `group`
         *     (not the exact status id), so `name` is the representative status name
         *     for that group (e.g. 護體 / 血契 / 靈契 / 中毒). `kind` distinguishes the
         *     source array: positive self-buffs (HP+0x288) vs debuffs (HP+0x4C4).
         */
        BuffInfo: {
            /** Group */
            group: number;
            /** Name */
            name: string;
            /**
             * Kind
             * @default buff
             * @enum {string}
             */
            kind: "buff" | "debuff";
        };
        /**
         * Character
         * @description Lightweight row used by GET /api/characters.
         */
        Character: {
            /** Pid */
            pid: number;
            /** Name */
            name?: string | null;
            /** Sect */
            sect?: string | null;
            /** Level */
            level?: number | null;
            /**
             * Link
             * @enum {string}
             */
            link: "ok" | "weak" | "lost";
        };
        /** CharacterDetail */
        CharacterDetail: {
            /** Pid */
            pid: number;
            /** Name */
            name: string;
            /** Sect */
            sect: string;
            /**
             * Link
             * @enum {string}
             */
            link: "ok" | "weak" | "lost";
            stats: components["schemas"]["CharacterStats"];
            vitals: components["schemas"]["Vitals"];
            position: components["schemas"]["Position"];
            autoclick: components["schemas"]["AutoClickStatus"];
            /**
             * Buffs
             * @default []
             */
            buffs: components["schemas"]["BuffInfo"][];
            /** Inventory */
            inventory?: components["schemas"]["Item"][] | null;
            /** Warehouse */
            warehouse?: components["schemas"]["Item"][] | null;
        };
        /**
         * CharacterRow
         * @description Used inside WorldSnapshot — stats summary per char.
         */
        CharacterRow: {
            /** Pid */
            pid: number;
            /** Name */
            name: string;
            /** Sect */
            sect: string;
            /**
             * Link
             * @enum {string}
             */
            link: "ok" | "weak" | "lost";
            /** Level */
            level: number;
            vitals: components["schemas"]["Vitals"];
            position: components["schemas"]["Position"];
            autoclick: components["schemas"]["AutoClickStatus"];
            /**
             * Buffs
             * @default []
             */
            buffs: components["schemas"]["BuffInfo"][];
        };
        /** CharacterStats */
        CharacterStats: {
            /** Level */
            level: number;
            /** Waigong */
            waigong: number;
            /** Neili */
            neili: number;
            /** Genggu */
            genggu: number;
            /** Shenfa */
            shenfa: number;
            /** Jiqiao */
            jiqiao: number;
            /** Xuanxue */
            xuanxue: number;
            /** Wugong */
            wugong: number;
            /** Wugong Base */
            wugong_base: number;
            /** Neijing */
            neijing: number;
            /** Fangyu */
            fangyu: number;
            /** Huji */
            huji: number;
            /** Mingzhong */
            mingzhong: number;
            /** Shanduo */
            shanduo: number;
        };
        /** ConnectOptions */
        ConnectOptions: {
            /**
             * Compat Mode
             * @default false
             */
            compat_mode: boolean;
            /**
             * Auto Chain
             * @default true
             */
            auto_chain: boolean;
        };
        /** ConnectRequest */
        ConnectRequest: {
            /** Hp */
            hp?: number | null;
            /**
             * @default {
             *       "compat_mode": false,
             *       "auto_chain": true
             *     }
             */
            options: components["schemas"]["ConnectOptions"];
        };
        /** ConnectResult */
        ConnectResult: {
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
            /** Hp Addr */
            hp_addr?: number | null;
        };
        /** CreateAccountRequest */
        CreateAccountRequest: {
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Item */
        Item: {
            /** Item Id */
            item_id: number;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /**
             * Source
             * @enum {string}
             */
            source: "inventory" | "warehouse";
        };
        /** KeepActiveStatus */
        KeepActiveStatus: {
            /** Running */
            running: boolean;
            /** Started At */
            started_at?: number | null;
            /** Runtime Seconds */
            runtime_seconds?: number | null;
            /** Last Send At */
            last_send_at?: number | null;
        };
        /** MapInfo */
        MapInfo: {
            stage: components["schemas"]["StageInfo"];
            /** Player X */
            player_x?: number | null;
            /** Player Y */
            player_y?: number | null;
            /**
             * Monsters
             * @default []
             */
            monsters: components["schemas"]["MapMonster"][];
            /**
             * Warps
             * @default []
             */
            warps: components["schemas"]["MapWarp"][];
            /**
             * Nearby
             * @default []
             */
            nearby: components["schemas"]["SpawnPoint"][];
        };
        /** MapMonster */
        MapMonster: {
            /** Npc Id */
            npc_id: number;
            /** Name */
            name?: string | null;
            /** Level */
            level?: number | null;
            /** Hp */
            hp?: number | null;
            /** Count */
            count: number;
            /** Drop Money Min */
            drop_money_min?: number | null;
            /** Drop Money Max */
            drop_money_max?: number | null;
            /** Drop Exp */
            drop_exp?: number | null;
        };
        /** MapWarp */
        MapWarp: {
            /** Dst Stage Id */
            dst_stage_id: number;
            /** Dst Name */
            dst_name?: string | null;
            /** Dst Tag */
            dst_tag?: number | null;
        };
        /** OkResponse */
        OkResponse: {
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** Position */
        Position: {
            /** Map Name */
            map_name?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RelocateRequest */
        RelocateRequest: {
            /** Hp */
            hp?: number | null;
        };
        /** SaveSnapshotRequest */
        SaveSnapshotRequest: {
            /** Pid */
            pid: number;
            /**
             * Source
             * @enum {string}
             */
            source: "inventory" | "warehouse";
        };
        /** SaveSnapshotResult */
        SaveSnapshotResult: {
            /** Saved */
            saved: boolean;
            /** Snapshot Id */
            snapshot_id?: number | null;
        };
        /** SetCharacterAccountRequest */
        SetCharacterAccountRequest: {
            /** Account Id */
            account_id: number | null;
        };
        /** SnapshotRow */
        SnapshotRow: {
            /** Snapshot Id */
            snapshot_id: number;
            /** Character Name */
            character_name: string;
            /** Account Id */
            account_id?: number | null;
            /**
             * Source
             * @enum {string}
             */
            source: "inventory" | "warehouse";
            /** Saved At */
            saved_at: string;
            /** Item Count */
            item_count: number;
        };
        /** SpawnPoint */
        SpawnPoint: {
            /** Npc Id */
            npc_id: number;
            /** Name */
            name?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Distance */
            distance?: number | null;
        };
        /** StageInfo */
        StageInfo: {
            /** Stage Id */
            stage_id: number;
            /** Name */
            name: string;
        };
        /** TreasuryHolder */
        TreasuryHolder: {
            /** Character */
            character: string;
            /**
             * Source
             * @enum {string}
             */
            source: "inventory" | "warehouse";
            /** Account */
            account?: string | null;
            /** Qty */
            qty: number;
        };
        /** TreasuryItem */
        TreasuryItem: {
            /** Item Id */
            item_id: number;
            /** Name */
            name: string;
            /**
             * Item Type
             * @default
             */
            item_type: string;
            /** Total Qty */
            total_qty: number;
            /** On Person */
            on_person: number;
            /** In Warehouse */
            in_warehouse: number;
            /** Holders */
            holders: components["schemas"]["TreasuryHolder"][];
        };
        /** TreasurySummary */
        TreasurySummary: {
            /** Total Kinds */
            total_kinds: number;
            /** Total Qty */
            total_qty: number;
            /** On Person */
            on_person: number;
            /** In Warehouse */
            in_warehouse: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vitals */
        Vitals: {
            /** Hp */
            hp: number;
            /** Hp Max */
            hp_max: number;
            /** Mp */
            mp: number;
            /** Mp Max */
            mp_max: number;
            /** Weight */
            weight: number;
            /** Weight Max */
            weight_max: number;
        };
        /** WorldSnapshot */
        WorldSnapshot: {
            /** Chars */
            chars: components["schemas"]["CharacterRow"][];
            /** Server Ts */
            server_ts: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_characters_api_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
        };
    };
    world_snapshot_api_world_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSnapshot"];
                };
            };
        };
    };
    character_detail_api_characters__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_char_api_characters__pid__connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_char_api_characters__pid__disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relocate_char_api_characters__pid__relocate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelocateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_char_api_characters__pid__rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    focus_window_api_characters__pid__focus_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_inventory_api_characters__pid__inventory_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_warehouse_api_characters__pid__warehouse_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_snapshots_get: {
        parameters: {
            query?: {
                account_id?: number | null;
                character_name?: string | null;
                source?: string | null;
                days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_snapshot_api_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveSnapshotResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_api_snapshots__snapshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_character_api_characters_by_name__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    create_account_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_character_account_api_characters_by_name__name__account_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCharacterAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_characters__pid__autoclick_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoClickConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_characters__pid__autoclick_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_click_api_characters__pid__autoclick_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoClickTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_characters__pid__autoclick_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoClickStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_characters__pid__keep_active_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_characters__pid__keep_active_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_characters__pid__keep_active_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeepActiveStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_by_name_api_maps_by_name__name__get: {
        parameters: {
            query?: {
                x?: number | null;
                y?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    treasury_summary_api_treasury_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreasurySummary"];
                };
            };
        };
    };
    treasury_items_api_treasury_items_get: {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreasuryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    treasury_export_csv_api_treasury_export_csv_get: {
        parameters: {
            query?: {
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_backup_api_backup_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_backup_api_backup_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_backup_api_backup_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
