// THIS FILE IS REGENERATED by `npm run gen-types` from /openapi.json once
// the dev backend is running. Manual content here is a temporary stub.
export type LinkStatus = 'ok' | 'weak' | 'lost';

export interface Vitals { hp: number; hp_max: number; mp: number; mp_max: number; weight: number; weight_max: number; }
export interface Position { map_name: string | null; x: number; y: number; }
export interface AutoClickStatus { running: boolean; started_at: number | null; runtime_seconds: number | null; last_click_at: number | null; }
export interface CharacterRow { pid: number; name: string; sect: string; link: LinkStatus; level: number; vitals: Vitals; position: Position; autoclick: AutoClickStatus; }
export interface WorldSnapshot { chars: CharacterRow[]; server_ts: number; }
