"""Fixed 補給 points: where a trip buys and sells. Generated by
scripts/survey_supply_points.py from the game DB; do not edit by hand except
`verified` (the date a point was checked in game).

kind "family": the 家族道具商. Its shop follows the family manor (and a
特貢令 in the bag raises it a tier): evaluated from FAMILY_MENUS at run time.
kind "general": a town shopkeeper with one gold shop (`shop`).
"""

from __future__ import annotations

from dataclasses import dataclass

# The 家族道具商's menus: 一般商店 / 特貢商店 (25106 needs a 特貢令).
FAMILY_MENUS = (25098, 25106)


@dataclass(frozen=True)
class SupplyPoint:
    kind: str  # family / general
    npc_id: int
    name: str
    stage: int
    stage_name: str
    tile: tuple[int, int]
    shop: int | None = None  # general: shops.id
    verified: str | None = None  # date checked in game (YYYY-MM-DD)


# One point a line, as the survey writes them.
# fmt: off
POINTS = (
    SupplyPoint(kind="family", npc_id=6376, name='家族道具商', stage=23, stage_name='檀泉別苑', tile=(70, 122), verified=None),
    SupplyPoint(kind="family", npc_id=6376, name='家族道具商', stage=51, stage_name='洛陽外城', tile=(70, 142), verified=None),
    SupplyPoint(kind="family", npc_id=6376, name='家族道具商', stage=53, stage_name='成都少城', tile=(41, 167), verified=None),
    SupplyPoint(kind="family", npc_id=6376, name='家族道具商', stage=207, stage_name='閻王門', tile=(37, 108), verified=None),
    SupplyPoint(kind="family", npc_id=6376, name='家族道具商', stage=216, stage_name='名劍山莊', tile=(44, 143), verified=None),
    SupplyPoint(kind="family", npc_id=6376, name='家族道具商', stage=231, stage_name='杭州城', tile=(45, 15), verified=None),
    SupplyPoint(kind="family", npc_id=6376, name='家族道具商', stage=243, stage_name='狐隱村', tile=(20, 27), verified=None),
    SupplyPoint(kind="family", npc_id=6376, name='家族道具商', stage=264, stage_name='曼陀羅城', tile=(94, 15), verified=None),
    SupplyPoint(kind="general", npc_id=6169, name='藏海村道具商', stage=9, stage_name='藏海村', tile=(50, 12), shop=15, verified=None),
    SupplyPoint(kind="general", npc_id=6488, name='藏海村道具商', stage=9, stage_name='藏海村', tile=(48, 11), shop=15, verified=None),
    SupplyPoint(kind="general", npc_id=6489, name='桃源境道具商', stage=18, stage_name='桃源境', tile=(23, 27), shop=19, verified=None),
    SupplyPoint(kind="general", npc_id=6130, name='檀泉道具商', stage=23, stage_name='檀泉別苑', tile=(23, 15), shop=16, verified=None),
    SupplyPoint(kind="general", npc_id=6121, name='天外天道具商', stage=30, stage_name='天外天境', tile=(20, 61), shop=18, verified=None),
    SupplyPoint(kind="general", npc_id=6490, name='峨嵋派道具商', stage=36, stage_name='峨嵋派', tile=(22, 67), shop=23, verified=None),
    SupplyPoint(kind="general", npc_id=6171, name='洛陽道具商', stage=51, stage_name='洛陽外城', tile=(53, 28), shop=21, verified=None),
    SupplyPoint(kind="general", npc_id=6171, name='洛陽道具商', stage=52, stage_name='洛陽內城', tile=(25, 29), shop=21, verified=None),
    SupplyPoint(kind="general", npc_id=6487, name='成都道具商', stage=54, stage_name='成都太城', tile=(79, 12), shop=17, verified=None),
    SupplyPoint(kind="general", npc_id=6063, name='流星村商人', stage=55, stage_name='流星雷島˙南', tile=(62, 40), shop=8, verified=None),
    SupplyPoint(kind="general", npc_id=6063, name='流星村商人', stage=56, stage_name='流星火島˙南', tile=(62, 40), shop=8, verified=None),
    SupplyPoint(kind="general", npc_id=6063, name='流星村商人', stage=57, stage_name='流星村', tile=(62, 40), shop=8, verified=None),
    SupplyPoint(kind="general", npc_id=6063, name='流星村商人', stage=158, stage_name='流星雷島˙北', tile=(62, 40), shop=8, verified=None),
    SupplyPoint(kind="general", npc_id=6063, name='流星村商人', stage=159, stage_name='流星火島˙北', tile=(62, 40), shop=8, verified=None),
    SupplyPoint(kind="general", npc_id=6063, name='流星村商人', stage=160, stage_name='流星冰島˙北', tile=(62, 40), shop=8, verified=None),
    SupplyPoint(kind="general", npc_id=6121, name='天外天道具商', stage=170, stage_name='天外天地下街', tile=(37, 22), shop=18, verified=None),
    SupplyPoint(kind="general", npc_id=6169, name='藏海村道具商', stage=172, stage_name='藏海村市集', tile=(3, 15), shop=15, verified=None),
    SupplyPoint(kind="general", npc_id=6487, name='成都道具商', stage=173, stage_name='成都市集', tile=(8, 28), shop=17, verified=None),
    SupplyPoint(kind="general", npc_id=6826, name='閻王門道具商', stage=207, stage_name='閻王門', tile=(88, 39), shop=40, verified=None),
    SupplyPoint(kind="general", npc_id=6745, name='無名村道具商', stage=213, stage_name='無名村', tile=(55, 70), shop=36, verified=None),
    SupplyPoint(kind="general", npc_id=6768, name='名劍道具商', stage=216, stage_name='名劍山莊', tile=(84, 36), shop=37, verified=None),
    SupplyPoint(kind="general", npc_id=6875, name='杭州道具商', stage=231, stage_name='杭州城', tile=(51, 141), shop=42, verified=None),
    SupplyPoint(kind="general", npc_id=7527, name='道具老闆', stage=264, stage_name='曼陀羅城', tile=(75, 13), shop=49, verified=None),
    SupplyPoint(kind="general", npc_id=6904, name='仙島道具商', stage=300, stage_name='南海碼頭', tile=(91, 27), shop=44, verified=None),
)
