"""Write services/supply_points.py: the fixed 補給 points, from the game DB.

Run again after a DB update. A point verified in game keeps its `verified`
date (matched by npc id and map); new points start unverified.

    uv run scripts/survey_supply_points.py

Points: every 家族道具商 (characters with a family manor buy there only),
every town shopkeeper whose gold shop sells potions or 回城捲軸, and every
錢莊伙計 (the warehouse, which also holds the 錢莊 silver). Shopkeepers
come from the dialogue (trigger A5 opens shops.id, the speaker's display name
finds the placed NPC; see services/shop_catalog.py).
"""

from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from services import route_plan as rp  # noqa: E402
from services.shop_catalog import load_catalog, warehouse_keepers  # noqa: E402

OUT = REPO / "services" / "supply_points.py"
FAMILY_NPC = 6376  # 家族道具商
STOCK_TYPES = ("POTION", "RETURN_SCROLL")

HEADER = '''"""Fixed 補給 points: where a trip buys and sells. Generated by
scripts/survey_supply_points.py from the game DB; do not edit by hand except
`verified` (the date a point was checked in game).

kind "family": the 家族道具商. Its shop follows the family manor (and a
特貢令 in the bag raises it a tier): evaluated from FAMILY_MENUS at run time.
kind "general": a town shopkeeper with one gold shop (`shop`).
kind "warehouse": a 錢莊伙計: opens the warehouse window (items and silver).
"""

from __future__ import annotations

from dataclasses import dataclass

# The 家族道具商's menus: 一般商店 / 特貢商店 (25106 needs a 特貢令).
FAMILY_MENUS = (25098, 25106)


@dataclass(frozen=True)
class SupplyPoint:
    kind: str  # family / general / warehouse
    npc_id: int
    name: str
    stage: int
    stage_name: str
    tile: tuple[int, int]
    shop: int | None = None  # general: shops.id
    verified: str | None = None  # date checked in game (YYYY-MM-DD)


# One point a line, as the survey writes them.
# fmt: off
POINTS = (
'''


def _old_verified() -> dict[tuple[int, int], str]:
    if not OUT.exists():
        return {}
    ns: dict = {}
    exec(compile(OUT.read_text(encoding="utf-8"), str(OUT), "exec"), ns)
    return {(p.npc_id, p.stage): p.verified for p in ns["POINTS"] if p.verified}


def main() -> None:
    cat = load_catalog()
    names = rp._tables().stages
    script = rp._Script(rp._tables(), 60, None)
    con = sqlite3.connect(REPO / "tthol.sqlite")
    marks = ",".join("?" * len(STOCK_TYPES))
    stock = {
        r[0] for r in con.execute(f"SELECT id FROM items WHERE type_name IN ({marks})", STOCK_TYPES)
    }
    con.close()
    verified = _old_verified()
    rows = []
    for npc in sorted(cat.npcs, key=lambda n: (n.npc_id != FAMILY_NPC, n.stage, n.npc_id)):
        v = verified.get((npc.npc_id, npc.stage))
        common = (
            f"npc_id={npc.npc_id}, name={npc.name!r}, stage={npc.stage},"
            f" stage_name={names.get(npc.stage, '#' + str(npc.stage))!r}, tile={npc.tile!r}"
        )
        if npc.npc_id == FAMILY_NPC:
            rows.append(f'    SupplyPoint(kind="family", {common}, verified={v!r}),')
            continue
        shops = sorted({s for m, s in npc.opens if s in script.shops_from_msg(m)})
        if len(shops) != 1:
            continue  # no shop, or one that depends on something a trip cannot check
        if not any(i in stock for i in cat.sells.get(shops[0], {})):
            continue  # weapons and the like
        rows.append(f'    SupplyPoint(kind="general", {common}, shop={shops[0]}, verified={v!r}),')
    for npc in sorted(warehouse_keepers(), key=lambda n: (n.stage, n.npc_id)):
        if "錢莊" not in npc.name or not any(script.opens_warehouse(m) for m, _s in npc.opens):
            continue  # quest NPCs (牧有虔) open it inside a story branch
        v = verified.get((npc.npc_id, npc.stage))
        common = (
            f"npc_id={npc.npc_id}, name={npc.name!r}, stage={npc.stage},"
            f" stage_name={names.get(npc.stage, '#' + str(npc.stage))!r}, tile={npc.tile!r}"
        )
        rows.append(f'    SupplyPoint(kind="warehouse", {common}, verified={v!r}),')
    OUT.write_text(HEADER + "\n".join(rows) + "\n)\n", encoding="utf-8")
    print(f"wrote {len(rows)} points to {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
